// browser/create-template/templates/nextjs-site/src/views/FullPage/BlogIndexPageFullPage.tsx
import Container from '@/components/Layout/Container';
import { website, type Page } from '@/ontologies/website';
import { core, type Resource } from '@tomic/lib';
import styles from './BlogIndexPageFullPage.module.css';
import VStack from '@/components/Layout/VStack';
import HStack from '@/components/Layout/HStack';
import ListItemView from '../ListItem/ListItemView';
import { getAllBlogposts } from '@/atomic/getAllBlogposts';
import { Suspense } from 'react';
import Searchbar from '@/components/Searchbar';
import { store } from '@/store';

const BlogIndexPageFullPage = async ({
  resource,
  searchParams,
}: {
  resource: Resource<Page>;
  searchParams?: {
    [key: string]: string | string[] | undefined;
  };
}) => {
  const allItems = await getAllBlogposts();
  let results: string[] = [];

  if (searchParams?.search && typeof searchParams.search === 'string') {
    results = await store.search(searchParams.search, {
      filters: {
        [core.properties.isA]: website.classes.blogpost,
      },
    });
  } else {
    results = allItems;
  }

  return (
    <Container>
      <div className={styles.wrapper}>
        <VStack>
          <HStack wrap fullWidth align='center' justify='space-between'>
            <h1>{resource.title}</h1>

            <Suspense
              fallback={
                <input
                  className={styles.input}
                  type='search'
                  aria-label='Search'
                  placeholder='Search blogposts...'
                />
              }
            >
              <Searchbar />
            </Suspense>
          </HStack>
          {results.length !== 0 ? (
            <ul>
              {results.map((post: string) => (
                <li key={post}>
                  <ListItemView subject={post} />
                </li>
              ))}
            </ul>
          ) : (
            <Container>
              <p>No results found.</p>
            </Container>
          )}
        </VStack>
      </div>
    </Container>
  );
};

export default BlogIndexPageFullPage;

// browser/create-template/templates/sveltekit-site/src/lib/views/FullPage/BlogIndexPageFullPage.svelte
<script lang="ts">
	import Container from '$lib/components/Layout/Container.svelte';
	import { website, type BlogIndexPage } from '$lib/ontologies/website';
	import { core, type Resource } from '@tomic/lib';
	import ListItemView from '../ListItem/ListItemView.svelte';
	import VStack from '$lib/components/Layout/VStack.svelte';
	import HStack from '$lib/components/Layout/HStack.svelte';
	import Searchbar from '$lib/components/Searchbar.svelte';
	import { throttle } from '$lib/utils';
	import { getAllBlogposts } from '$lib/atomic/getAllBlogposts';
	import { getStoreFromContext } from '@tomic/svelte';

	interface Props {
		resource: Resource<BlogIndexPage>;
	}

	const { resource }: Props = $props();

	const store = getStoreFromContext();

	let allItems = $state<string[]>([]);
	let results = $state<string[]>([]);

	// We create a collection that collects all resources with the blogpost class. Sorted by publishedAt in descending order.
	getAllBlogposts().then((members) => {
		allItems = members;
		results = members;
	});

	const search = throttle(async (searchValue: string) => {
		if (searchValue === '') {
			results = allItems;
			return;
		}

		results = await store.search(searchValue, {
			filters: {
				[core.properties.isA]: website.classes.blogpost
			}
		});
	}, 200);
</script>

<Container>
	<div class="wrapper">
		<VStack>
			<HStack wrap fullWidth align="center" justify="space-between">
				<h1>{resource.title}</h1>
				<Searchbar placeholder="Search blogposts..." oninput={search} />
			</HStack>
			{#if results.length === 0}
				<p>No results found</p>
			{/if}
			<ul>
				{#each results as item (item)}
					<li>
						<ListItemView subject={item} />
					</li>
				{/each}
			</ul>
		</VStack>
	</div>
</Container>

<style>
	.wrapper {
		padding: 1rem;
	}

	ul {
		display: grid;
		grid-template-columns: repeat(
			auto-fill,
			minmax(calc(var(--theme-size-container-width) / 3 - 4rem), 1fr)
		);
		gap: 1rem;
		list-style-type: none;
		padding: 0;
	}
</style>
