// browser/create-template/templates/nextjs-site/src/views/FullPage/BlogpostFullPage.tsx
import Container from '@/components/Layout/Container';
import type { Blogpost } from '@/ontologies/website';
import { Resource } from '@tomic/lib';
import styles from './BlogpostFullPage.module.css';
import { Image } from '@/components/Image';
import { MarkdownContent } from '@/components/MarkdownContent';

const formatter = new Intl.DateTimeFormat('default', {
  year: 'numeric',
  month: 'long',
  day: 'numeric',
});

const BlogpostFullPage = ({ resource }: { resource: Resource<Blogpost> }) => {
  const date = resource.props.publishedAt
    ? formatter.format(new Date(resource.props.publishedAt))
    : undefined;

  return (
    <Container>
      <div className={styles.blogWrapper}>
        {resource.props.coverImage && (
          <div className={styles.coverImageWrapper}>
            <Image subject={resource.props.coverImage} alt='' />
          </div>
        )}
        <div className={styles.content}>
          <h1 className={styles.h1}>{resource.title}</h1>
          {date && <p className={styles.publishDate}>{date}</p>}
          <MarkdownContent
            subject={resource.subject}
            initialValue={resource.props.description}
          />
        </div>
      </div>
    </Container>
  );
};

export default BlogpostFullPage;

// browser/create-template/templates/sveltekit-site/src/lib/views/FullPage/BlogpostFullPage.svelte
<script lang="ts">
	import Container from '$lib/components/Layout/Container.svelte';
	import type { Blogpost } from '$lib/ontologies/website';
	import type { Resource } from '@tomic/lib';
	import { Image } from '@tomic/svelte';
	import SvelteMarkdown from 'svelte-markdown';

	interface Props {
		resource: Resource<Blogpost>;
	}

	const { resource }: Props = $props();

	const formatter = new Intl.DateTimeFormat('default', {
		year: 'numeric',
		month: 'long',
		day: 'numeric'
	});

	let date = $derived(formatter.format(new Date(resource.props.publishedAt)));
</script>

<Container>
	<div class="blog-wrapper">
		<Image subject={resource.props.coverImage} alt="" />
		<div class="content">
			<h1>{resource.title}</h1>
			<p class="publish-date">
				{date}
			</p>
			<SvelteMarkdown source={resource.props.description} />
		</div>
	</div>
</Container>

<style>
	.blog-wrapper {
		padding: 1rem;
		:global(& > picture > img) {
			width: 100%;
			height: 25rem;
			object-fit: cover;
			border-radius: var(--theme-border-radius);
		}
	}

	.publish-date {
		color: var(--theme-color-text-light);
		margin-bottom: 2rem;
	}
	.content {
		max-width: 70ch;
		margin: auto;
	}
</style>
