// pauseai-crm/crm/browser/create-template/templates/nextjs-site/src/views/FullPage/FullPageView.tsx
import { website } from '@/ontologies/website';
import PageFullPage from './PageFullPage';
import BlogIndexPageFullPage from './BlogIndexPageFullPage';
import BlogpostFullPage from './BlogpostFullPage';
import DefaultFullPage from './DefaultFullPage';
import { store } from '@/store';

const FullPageView = async ({
  subject,
  lang,
  searchParams,
}: {
  subject: string;
  lang?: string;
  searchParams?: Record<string, string | string[] | undefined>;
}) => {
  const resource = await store.getResource(subject);

  // Pick a component based on the resource's class.
  const Component = resource.matchClass(
    {
      [website.classes.page]: PageFullPage,
      [website.classes.blogIndexPage]: BlogIndexPageFullPage,
      [website.classes.blogpost]: BlogpostFullPage,
    },
    DefaultFullPage,
  );

  return <Component resource={resource} lang={lang} searchParams={searchParams} />;
};

export default FullPageView;

// browser/create-template/templates/sveltekit-site/src/lib/views/FullPage/FullPageView.svelte
<script lang="ts">
	import { website } from '$lib/ontologies/website';
	import { getResource } from '@tomic/svelte';
	import PageFullPage from './PageFullPage.svelte';
	import DefaultFullPage from './DefaultFullPage.svelte';
	import BlogIndexPageFullPage from './BlogIndexPageFullPage.svelte';
	import BlogpostFullPage from './BlogpostFullPage.svelte';

	/*
		Renders a full page view. The actual view component is determined by the resource's class.
	*/

	interface Props {
		subject: string;
		lang?: string;
	}

	const { subject, lang }: Props = $props();

	let resource = getResource(() => subject);

	let View = $derived(
		resource.matchClass(
			{
				[website.classes.page]: PageFullPage,
				[website.classes.blogIndexPage]: BlogIndexPageFullPage,
				[website.classes.blogpost]: BlogpostFullPage
			},
			DefaultFullPage
		)
	);
</script>

{#if View === BlogIndexPageFullPage}
	<BlogIndexPageFullPage {resource} {lang} />
{:else}
	<View {resource} />
{/if}
