// browser/create-template/templates/sveltekit-site/src/lib/components/Searchbar.svelte
<script lang="ts">
	import FaMagnifyingGlass from './Icons/FaMagnifyingGlass.svelte';
	import HStack from './Layout/HStack.svelte';

	interface Props {
		value?: string;
		placeholder: string;
	}

	let { value = $bindable(''), placeholder }: Props = $props();
</script>

<div class="search-bar">
	<HStack align="center" gap="1ch">
		<FaMagnifyingGlass />
		<input
			type="search"
			bind:value
			{placeholder}
		/>
	</HStack>
</div>

<style>
	.search-bar {
		border: 1px solid var(--theme-color-bg-1);
		border-radius: 10rem;
		padding-inline: 1rem;

		&:focus-within {
			box-shadow: 0px 0px 0px 2px var(--theme-color-accent);
		}
		:global(& svg) {
			width: 1rem;
			fill: var(--theme-color-text-light);
		}
	}

	input {
		height: 2rem;
		appearance: none;
		border: none;
		outline: none;
		background: none;
		background-color: transparent;
	}
</style>

// browser/create-template/templates/nextjs-site/src/components/Searchbar.tsx
'use client';

import HStack from './Layout/HStack';
import styles from './Searchbar.module.css';
import FaMagnifyingGlass from './Icons/magnifying-glass-solid.svg';
import Image from 'next/image';

const Searchbar = ({
  value,
  onChange,
}: {
  value: string;
  onChange: (value: string) => void;
}) => {
  return (
    <div className={styles.searchBar}>
      <HStack align='center' gap='1ch'>
        <Image
          priority
          width={16}
          height={16}
          src={FaMagnifyingGlass}
          alt='search'
        />
        <input
          className={styles.input}
          type='search'
          value={value}
          onChange={e => {
            onChange(e.target.value);
          }}
          aria-label='Search blogposts...'
          placeholder='Search blogposts...'
        />
      </HStack>
    </div>
  );
};

export default Searchbar;
