// browser/create-template/templates/nextjs-site/src/views/Block/BlockView.tsx
import DefaultView from '../DefaultView';
import TextBlock from './TextBlock';
import { website } from '@/ontologies/website';
import ImageGalleryBlock from './ImageGalleryBlock';
import { store } from '@/store';

const BlockView = async ({ subject }: { subject: string }) => {
  const block = await store.getResource(subject);

  const Component = block.matchClass(
    {
      [website.classes.textBlock]: TextBlock,
      [website.classes.imageGalleryBlock]: ImageGalleryBlock,
    },
    DefaultView,
  );

  return <Component resource={block} />;
};

export default BlockView;

// pauseai-crm/crm/browser/create-template/templates/sveltekit-site/src/lib/views/Block/BlockView.svelte
<script lang="ts">
	import { website } from '$lib/ontologies/website';
	import { getResource } from '@tomic/svelte';
	import DefaultView from '../DefaultView.svelte';
	import TextBlock from './TextBlock.svelte';
	import ImageGalleryBlock from './ImageGalleryBlock.svelte';

	interface Props {
		subject: string;
	}

	const { subject }: Props = $props();

	let block = getResource(() => subject);

	let View = $derived(
		block.matchClass(
			{
				[website.classes.textBlock]: TextBlock,
				[website.classes.imageGalleryBlock]: ImageGalleryBlock
			},
			DefaultView
		)
	);
</script>

<View resource={block} />
