// browser/create-template/templates/sveltekit-site/src/lib/views/ListItem/ListItemView.svelte
<script lang="ts">
	import { website } from '$lib/ontologies/website';
	import { getResource } from '@tomic/svelte';
	import DefaultView from '../DefaultView.svelte';
	import BlogListItem from './BlogListItem.svelte';

	interface Props {
		subject: string;
	}

	const { subject }: Props = $props();

	let listItem = getResource(() => subject);

	let View = $derived(
		listItem.matchClass(
			{
				[website.classes.blogpost]: BlogListItem
			},
			DefaultView
		)
	);
</script>

<View resource={listItem} />

// browser/create-template/templates/nextjs-site/src/views/ListItem/ListItemView.tsx
import { website } from '@/ontologies/website';
import BlogListItem from './BlogListItem';
import DefaultView from '@/views/DefaultView';
import { store } from '@/store';

const ListItemView = async ({
  subject,
  lang,
}: {
  subject: string;
  lang?: string;
}) => {
  const listItem = await store.getResource(subject);

  const Component = listItem.matchClass(
    {
      [website.classes.blogpost]: BlogListItem,
    },
    DefaultView,
  );

  return <Component resource={listItem} lang={lang} />;
};

export default ListItemView;
