// browser/create-template/templates/nextjs-site/src/components/Footer.tsx
import Container from './Layout/Container';
import HStack from './Layout/HStack';
import LanguageSwitcher from './LanguageSwitcher';
import { CmsEditLink } from './CmsEditor';
import styles from './Footer.module.css';

const Footer = () => {
  const year = new Date().getFullYear();

  return (
    <footer className={styles.footer}>
      <Container>
        <HStack align='center' justify='space-between' wrap>
          <p>&copy; {year} Your Company</p>
          <HStack align='center' gap='1rem' wrap>
            <a className={styles.link} href='/rss.xml'>
              RSS
            </a>
            <CmsEditLink />
            <LanguageSwitcher />
          </HStack>
        </HStack>
      </Container>
    </footer>
  );
};

export default Footer;

// pauseai-crm/crm/browser/create-template/templates/sveltekit-site/src/lib/components/Footer.svelte
<script lang="ts">
	import Container from './Layout/Container.svelte';
	import { appState } from '$lib/stores/appstate.svelte';
	import { getLanguageLinks, type LanguageLink } from '$lib/atomic/i18n';

	const year = new Date().getFullYear();

	let links = $state<LanguageLink[]>([]);

	// Build links to the current page in each of the website's languages.
	$effect(() => {
		const subject = appState.currentSubject;
		let cancelled = false;

		getLanguageLinks(subject).then((languageLinks) => {
			if (!cancelled) {
				links = languageLinks;
			}
		});

		return () => {
			cancelled = true;
		};
	});
</script>

<footer>
	<Container>
		<div class="row">
			<p>© {year} Your Company</p>
			{#if links.length > 1}
				<ul>
					{#each links as link (link.lang)}
						<li>
							<a href={link.href} hreflang={link.lang}>{link.lang}</a>
						</li>
					{/each}
				</ul>
			{/if}
		</div>
	</Container>
</footer>

<style>
	footer {
		background-color: var(--theme-color-bg-2);
		color: var(--theme-color-text-light);
	}

	.row {
		display: flex;
		align-items: center;
		justify-content: space-between;
		flex-wrap: wrap;
	}

	p {
		padding: 1rem;
	}

	ul {
		display: flex;
		gap: 0.5rem;
		list-style: none;
		padding: 1rem;
		margin: 0;
		text-transform: uppercase;
	}

	a {
		color: inherit;
	}
</style>
