// browser/create-template/templates/sveltekit-site/src/lib/views/Block/TextBlock.svelte
<script lang="ts">
	import type { TextBlock } from '$lib/ontologies/website';
	import type { Resource } from '@tomic/lib';
	import SvelteMarkdown from 'svelte-markdown';

	interface Props {
		resource: Resource<TextBlock>;
	}

	const { resource }: Props = $props();
</script>

<div class="wrapper">
	<SvelteMarkdown source={resource.props.description} />
</div>

<style>
	.wrapper {
		max-width: 70ch;
	}
</style>

// pauseai-crm/crm/browser/create-template/templates/nextjs-site/src/views/Block/TextBlock.tsx
import { Resource } from '@tomic/react';
import { MarkdownContent } from '@/components/MarkdownContent';
import type { TextBlock as TextBlockType } from '@/ontologies/website';

const TextBlock = ({ resource }: { resource: Resource<TextBlockType> }) => {
  return (
    <MarkdownContent
      subject={resource.subject}
      initialValue={resource.props.description}
    />
  );
};

export default TextBlock;
